# Generated by Django 5.2.4 on 2025-07-22 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("docs", "0002_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="Вопрос")),
                (
                    "answer_first",
                    models.CharField(max_length=200, verbose_name="Ответ_1"),
                ),
                (
                    "answer_second",
                    models.CharField(max_length=200, verbose_name="Ответ_2"),
                ),
                (
                    "answer_third",
                    models.CharField(max_length=200, null=True, verbose_name="Ответ_3"),
                ),
                (
                    "right_answer",
                    models.CharField(max_length=200, verbose_name="Правильный ответ"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="docs.lesson",
                        verbose_name="Материал теста",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тест",
                "verbose_name_plural": "Тесты",
            },
        ),
    ]
